import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className=" text-3xl text-white ">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 

           {/* ----------  */}
              <Navbar/>
           {/* ----------- */}
      <main className=" ">
        <section className="sm:pt-40 pt-28 flex justify-between  sm:flex-flow flex-wrap  w-full   ">
          {/*  top */}
          <div className=" sm:pl-20  z-10 ">
            <h2 className=" sm:text-7xl  text-4xl sm:w-[40rem] w-11/12 font-bold sm:text-left text-center sm:m-0 m-auto leading-normal" > Explore, Buy and Sell the <span className=" text-primary "> Best <br/> NFTs!</span>  </h2>
            <div className=" mt-10 text-lg flex sm:justify-start justify-center flex-wrap my-2 "> 
             <button className=" py-2 px-14 bg-primary text-black font-medium "> Explore</button>
             <button className=" py-2 px-14 bg-primary   font-medium  ml-4 border-primary border text-white bg-blure/50  "> Create</button>
          </div>
          </div>
          {/* bottom */}
          <div className=" z-0 bg-blure/50 sm:w-2/5 w-full   sm:h-[40rem] sm:-mt-40 -mt-7 flex justify-center items-center align-middle sm:pb-0 pb-20 ">
               <div className="w-[20rem] h-[25rem]   flex justify-center items-center align-middle sm:-ml-36 sm:mt-36  mt-20   "> 
                 <Image   alt="HeroImage" src='/Heroimage.jpg' width='400px' height='500' />
                </div>
          </div>
        </section>
      </main>
    </div>
  );
}
