import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className=" text-3xl text-white ">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 

           {/* ----------  */}
              <Navbar/>
           {/* ----------- */}
      <main className=" ">
        <section className="pt-40  flex -z-10 pl-16 ">
          {/*  top */}
          <div>
            <h2 className=" text-7xl w-[40rem] leading-normal" > Explore, Buy and Sell the <span className=" text-primary "> Best <br/> NFTs!</span>  </h2>
            <div className=" mt-10 text-lg "> 
             <button className=" py-2 px-14 bg-primary text-black font-medium "> Explore</button>
             <button className=" py-2 px-14 bg-primary  font-medium  ml-4 border-primary border text-white bg-blure/50  "> Create</button>
          </div>
          </div>
          {/* bottom */}
          <div className=" bg-blure/50 w-2/4 h-[40rem] -mt-40 ">

          </div>
        </section>
      </main>
    </div>
  );
}
